# This file configures the $GKE_APP_NAME app which serves public web traffic on port 80
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-samurai-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-samurai-crud
  template:
    metadata:
      labels:
        app: health-samurai-crud
    spec:
      containers:
        - name: health-samurai-crud
          image: gcr.io/river-bruin-366614/health-samurai
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
