#!/bin/sh

project_id=$1 || exit; shift

project_name=$1 || exit; shift

PATH=$PATH:google-cloud-sdk/bin # For gke-gcloud-auth-plugin.

# Link as seen by https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=google-cloud-sdk-gke-gcloud-auth-plugin.
# https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke.
curl -o plugin.tar.gz https://storage.googleapis.com/cloud-sdk-release/for_packagers/linux/google-cloud-cli-gke-gcloud-auth-plugin_406.0.0.orig_amd64.tar.gz
tar xf plugin.tar.gz
# Now gke-gcloud-auth-plugin is in our PATH.

gcloud auth login
# shellcheck disable=SC2086
gcloud config set project "${project_id}"
#gcloud compute zones list
gcloud config set compute/zone us-west1-a
#gcloud container clusters list
gcloud container clusters create "${project_name}"
gcloud container clusters get-credentials
# Verify.
gcloud container clusters list
kubectl config get-contexts

## Docker.
docker image build -t clj-on-k8s/health_samurai .
docker run -p 3000:3000 clj-on-k8s/health_samurai

gcloud projects list

docker tag clj-on-k8s/health_samurai gcr.io/"${project_id}"/health_samurai
gcloud auth configure-docker
docker push gcr.io/"${project_id}"/health_samurai

# Verify
gcloud container images list-tags gcr.io/"${project_id}"/health_samurai
kubectl run health-samurai --image gcr.io/river-bruin-366614/health_samurai --port 3000

#docker build .
