apiVersion: v1
kind: Service
metadata:
  name: health-samurai-service
spec:
  type: LoadBalancer
  loadBalancerIP: $IP_WEB
  selector:
    app: health-samurai-crud
  ports:
    - port: 80
      targetPort: 80
