# This file configures the $GKE_APP_NAME app which serves public web traffic on port 80
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-samurai-crud
spec:
  replicas: 1
  selector:
    matchLabels:s
      app: health-samurai-crud
  template:
    metadata:
      labels:
        app: health-samurai-crud
    spec:
      containers:
        - name: health-samurai-crud
          image: gcr.io/proud-matter-369215/health-samurai:$GITHUB_SHA
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: DB_HOST
              value: "34.142.125.92"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"