# This file configures the $GKE_APP_NAME app which serves public web traffic on port 80
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $GKE_APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $GKE_APP_NAME
  template:
    metadata:
      labels:
        app: $GKE_APP_NAME
    spec:
      containers:
        - name: $GKE_APP_NAME
          imag e: gcr.io/$GKE_PROJECT/health-samurai:$GITHUB_SHA
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
