name: Deploy-GKE

on:
  push:
    branches: [ "master" ]

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: health-samurai-cluster
  GKE_APP_NAME: health-samurai-crud
  GKE_SERVICE: health-samurai-service
  GKE_SERVICE_ACCOUNT: health-samurai-serviceaccount
  GKE_DEPLOYMENT_NAME: health-samurai-crud-deployment
  GKE_REGION: europe-west3
  GKE_ZONE: europe-west3-a
  
jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.6.0
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
        export_default_credentials: true 

    # Build the Docker image
    - name: Build and Push
      working-directory: .
      run: |-
        docker image build -t clj-on-k8s/health-samurai .
        docker tag clj-on-k8s/health-samurai gcr.io/$GKE_PROJECT/health-samurai
        docker push gcr.io/$GKE_PROJECT/health-samurai
  Deploy:
    runs-on: ubuntu-latest
    environment: prod
    needs: Build

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.6.0
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
        export_default_credentials: true 

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v0.5.0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Deploy the new Docker image to the GKE cluster
    - name: Deploy
      working-directory: .
      run: |-
        envsubst < Service.yml | kubectl apply -f -
        envsubst < Deployment.yml | kubectl apply -f -
